sonar.projectKey=spontaine-demo
sonar.projectName=Spontaine Demo
sonar.projectVersion=1.0

sonar.sources=.

sonar.sourceEncoding=UTF-8

sonar.host.url=https://b2f7-2401-4900-8fde-5280-49b6-3600-448c-3d18.ngrok-free.app
sonar.login=sqa_fb04c74f52d03eeecbb807a0e98fc7fa5f2acc27
