<?php

namespace App\Services\User;

class RoleList
{
    const ROLES = [
        [
            'role' => 'ADMIN',
            'superUser' => true,
            'permissions' => [],
        ],
        [
            'role' => 'HELPDESK',
            'superUser' => false,
            'permissions' => [
                ['permission' => 'tickets.viewAny', 'customRules' => []],
                ['permission' => 'tickets.view', 'customRules' => []],
                ['permission' => 'tickets.updateStatus', 'customRules' => []],
                ['permission' => 'tickets.updateAssignment', 'customRules' => []],
            ],
        ],
        [
            'role' => 'HELPDESK PLUS',
            'superUser' => false,
            'permissions' => [
                ['permission' => 'tickets.viewAny', 'customRules' => []],
                ['permission' => 'tickets.view', 'customRules' => []],
                ['permission' => 'tickets.updateStatus', 'customRules' => []],
                ['permission' => 'tickets.updateAssignment', 'customRules' => []],
                ['permission' => 'tickets.updateDepartment', 'customRules' => []],
                ['permission' => 'tickets.updateUser', 'customRules' => []],
            ],
        ],
        [
            'role' => 'Space Queue Manager',
            'superUser' => false,
            'permissions' => [
                ['permission' => 'spaceConfig.viewAny', 'customRules' => []],
                ['permission' => 'spaceConfig.view', 'customRules' => []],
                ['permission' => 'spaceConfig.create', 'customRules' => []],
                ['permission' => 'spaceConfig.update', 'customRules' => []],
                ['permission' => 'spaceConfig.delete', 'customRules' => []],
                ['permission' => 'spaceRequestCompany.viewAny', 'customRules' => []],
                ['permission' => 'spaceRequestCompany.view', 'customRules' => []],
                ['permission' => 'spaceRequestCompany.create', 'customRules' => []],
                ['permission' => 'spaceRequestCompany.update', 'customRules' => []],
                ['permission' => 'spaceRequestCompany.delete', 'customRules' => []],
                ['permission' => 'spaceRequest.viewAny', 'customRules' => []],
                ['permission' => 'spaceRequest.view', 'customRules' => []],
                ['permission' => 'spaceRequest.create', 'customRules' => []],
                ['permission' => 'spaceRequest.update', 'customRules' => []],
                ['permission' => 'spaceRequest.delete', 'customRules' => []],
                // 'spaceConfig.viewAny',
                // 'spaceConfig.view',
                // 'spaceConfig.create',
                // 'spaceConfig.update',
                // 'spaceConfig.delete',
                // 'spaceRequestCompany.viewAny',
                // 'spaceRequestCompany.view',
                // 'spaceRequestCompany.create',
                // 'spaceRequestCompany.update',
                // 'spaceRequestCompany.delete',
                // 'spaceRequest.viewAny',
                // 'spaceRequest.view',
                // 'spaceRequest.create',
                // 'spaceRequest.update',
                // 'spaceRequest.delete',
            ],
        ],
        [
            'role' => 'FACILITIES BOOKING & EVENT MANAGER',
            'superUser' => false,
            'permissions' => [
                //reservation permissions
                ['permission' => 'reservation.viewAny', 'customRules' => []],
                ['permission' => 'reservation.view', 'customRules' => []],
                ['permission' => 'reservation.create', 'customRules' => []],
                ['permission' => 'reservation.update', 'customRules' => []],
                ['permission' => 'reservation.updateStatus', 'customRules' => []],
                ['permission' => 'reservation.internalNotes', 'customRules' => []],
                ['permission' => 'reservation.amenities', 'customRules' => []],
                ['permission' => 'reservation.partialCancellation', 'customRules' => []],
                ['permission' => 'reservation.payment', 'customRules' => []],
                ['permission' => 'reservation.delete', 'customRules' => []],
                //payments permission
                ['permission' => 'payments.viewAny', 'customRules' => []],
                ['permission' => 'payments.view', 'customRules' => []],
                ['permission' => 'payments.create', 'customRules' => []],
                ['permission' => 'payments.update', 'customRules' => []],
                ['permission' => 'payments.delete', 'customRules' => []],
                //spaces permission
                ['permission' => 'space.viewAny', 'customRules' => []],
                ['permission' => 'space.view', 'customRules' => []],
                ['permission' => 'space.create', 'customRules' => []],
                ['permission' => 'space.update', 'customRules' => []],
                ['permission' => 'space.delete', 'customRules' => []],
                //location permission
                ['permission' => 'location.viewAny', 'customRules' => []],
                ['permission' => 'location.view', 'customRules' => []],
                ['permission' => 'location.create', 'customRules' => []],
                ['permission' => 'location.update', 'customRules' => []],
                ['permission' => 'location.delete', 'customRules' => []],
                //amenities permission
                ['permission' => 'amenity.viewAny', 'customRules' => []],
                ['permission' => 'amenity.view', 'customRules' => []],
                ['permission' => 'amenity.create', 'customRules' => []],
                ['permission' => 'amenity.update', 'customRules' => []],
                ['permission' => 'amenity.delete', 'customRules' => []],
                //price plans permission
                ['permission' => 'pricePlan.viewAny', 'customRules' => []],
                ['permission' => 'pricePlan.view', 'customRules' => []],
                ['permission' => 'pricePlan.create', 'customRules' => []],
                ['permission' => 'pricePlan.update', 'customRules' => []],
                ['permission' => 'pricePlan.delete', 'customRules' => []],
                //unavailability permission
                ['permission' => 'unavailability.viewAny', 'customRules' => []],
                ['permission' => 'unavailability.view', 'customRules' => []],
                ['permission' => 'unavailability.create', 'customRules' => []],
                ['permission' => 'unavailability.update', 'customRules' => []],
                ['permission' => 'unavailability.delete', 'customRules' => []],
                //calendar permission
                ['permission' => 'activity.viewAny', 'customRules' => []],
                ['permission' => 'activity.view', 'customRules' => []],
                ['permission' => 'activity.create', 'customRules' => []],
                ['permission' => 'activity.update', 'customRules' => []],
                ['permission' => 'activity.delete', 'customRules' => []],
                ['permission' => 'activity.publish', 'customRules' => []],

                ['permission' => 'page.view', 'customRules' => []],
                ['permission' => 'page.create', 'customRules' => []],
                ['permission' => 'page.update', 'customRules' => []],
                ['permission' => 'page.delete', 'customRules' => []],
                ['permission' => 'page.publish', 'customRules' => []],
            ],
        ],
        [
            'role' => 'Company Admin',
            'superUser' => false,
            'permissions' => [
                // 'location.viewAny',
                // 'location.view',
                // 'location.create',
                // 'location.update',
                // 'location.delete',
                // 'building.viewAny',
                // 'building.view',
                // 'building.create',
                // 'building.update',
                // 'building.delete',
                // 'company.viewAny',
                // 'company.view',
                // 'company.create',
                // 'company.update',
                // 'company.delete',
                ['permission' => 'company.viewAny', 'customRules' => []],
                ['permission' => 'company.view', 'customRules' => []],
                ['permission' => 'company.create', 'customRules' => []],
                ['permission' => 'company.update', 'customRules' => []],
                ['permission' => 'company.delete', 'customRules' => []],
            ],
        ],
        [
            'role' => 'CONTENT CREATOR',
            'superUser' => false,
            'permissions' => [
                //announcement permissions
                ['permission' => 'announcement.viewAny', 'customRules' => []],
                ['permission' => 'announcement.view', 'customRules' => []],
                ['permission' => 'announcement.create', 'customRules' => []],
                ['permission' => 'announcement.update', 'customRules' => []],
                ['permission' => 'announcement.delete', 'customRules' => []],
                ['permission' => 'announcement.removeFile', 'customRules' => []],
                ['permission' => 'announcement.attachFile', 'customRules' => []],
                //page permissions
                ['permission' => 'page.viewAny', 'customRules' => []],
                ['permission' => 'page.view', 'customRules' => []],
                ['permission' => 'page.create', 'customRules' => []],
                ['permission' => 'page.update', 'customRules' => []],
                ['permission' => 'page.delete', 'customRules' => []],
                //article permissions
                ['permission' => 'article.viewAny', 'customRules' => []],
                ['permission' => 'article.view', 'customRules' => []],
                ['permission' => 'article.create', 'customRules' => []],
                ['permission' => 'article.update', 'customRules' => []],
                ['permission' => 'article.delete', 'customRules' => []],
                //activities permissions
                ['permission' => 'activity.viewAny', 'customRules' => []],
                ['permission' => 'activity.view', 'customRules' => []],
                ['permission' => 'activity.create', 'customRules' => []],
                ['permission' => 'activity.update', 'customRules' => []],
                ['permission' => 'activity.delete', 'customRules' => []],
                //video image document permission
                ['permission' => 'video.manage', 'customRules' => []],
                ['permission' => 'image.manage', 'customRules' => []],
                ['permission' => 'document.manage', 'customRules' => []],
                //gallery
                ['permission' => 'gallery', 'customRules' => []],
                ['permission' => 'nav', 'customRules' => []],
                ['permission' => 'footer', 'customRules' => []],
            ],
        ],
        [
            'role' => 'CONTENT ADMIN',
            'superUser' => false,
            'permissions' => [
                //announcement permissions
                ['permission' => 'announcement.viewAny', 'customRules' => []],
                ['permission' => 'announcement.view', 'customRules' => []],
                ['permission' => 'announcement.create', 'customRules' => []],
                ['permission' => 'announcement.update', 'customRules' => []],
                ['permission' => 'announcement.delete', 'customRules' => []],
                ['permission' => 'announcement.removeFile', 'customRules' => []],
                ['permission' => 'announcement.attachFile', 'customRules' => []],
                ['permission' => 'announcement.publish', 'customRules' => []],
                //page permissions
                ['permission' => 'page.viewAny', 'customRules' => []],
                ['permission' => 'page.view', 'customRules' => []],
                ['permission' => 'page.create', 'customRules' => []],
                ['permission' => 'page.update', 'customRules' => []],
                ['permission' => 'page.delete', 'customRules' => []],
                ['permission' => 'page.publish', 'customRules' => []],
                //article permissions
                ['permission' => 'article.viewAny', 'customRules' => []],
                ['permission' => 'article.view', 'customRules' => []],
                ['permission' => 'article.create', 'customRules' => []],
                ['permission' => 'article.update', 'customRules' => []],
                ['permission' => 'article.delete', 'customRules' => []],
                ['permission' => 'article.publish', 'customRules' => []],
                //activities permissions
                ['permission' => 'activity.viewAny', 'customRules' => []],
                ['permission' => 'activity.view', 'customRules' => []],
                ['permission' => 'activity.create', 'customRules' => []],
                ['permission' => 'activity.update', 'customRules' => []],
                ['permission' => 'activity.delete', 'customRules' => []],
                ['permission' => 'activity.publish', 'customRules' => []],
                //video image document permission
                ['permission' => 'video.manage', 'customRules' => []],
                ['permission' => 'image.manage', 'customRules' => []],
                ['permission' => 'document.manage', 'customRules' => []],
                //gallery
                ['permission' => 'gallery', 'customRules' => []],
                ['permission' => 'gallery.publish', 'customRules' => []],
                ['permission' => 'nav', 'customRules' => []],
                ['permission' => 'footer', 'customRules' => []],
            ],
        ],
        [
            'role' => 'ANNOUNCEMENT MANAGER',
            'superUser' => false,
            'permissions' => [
                ['permission' => 'notification', 'customRules' => []],
            ],
        ],
        [
            'role' => 'EXTERNAL CONTENT MANAGER',
            'superUser' => false,
            'permissions' => [
                //article permissions
                ['permission' => 'article.viewAny', 'customRules' => []],
                ['permission' => 'article.view', 'customRules' => []],
                ['permission' => 'article.create', 'customRules' => []],
                ['permission' => 'article.update', 'customRules' => []],
                ['permission' => 'article.delete', 'customRules' => []],
                //activities permissions
                ['permission' => 'activity.viewAny', 'customRules' => []],
                ['permission' => 'activity.view', 'customRules' => []],
                ['permission' => 'activity.create', 'customRules' => []],
                ['permission' => 'activity.update', 'customRules' => []],
                ['permission' => 'activity.delete', 'customRules' => []],
            ],
        ],
        [
            'role' => 'JOB PORTAL MANAGER',
            'superUser' => false,
            'permissions' => [
                ['permission' => 'job.viewAny', 'customRules' => []],
                ['permission' => 'job.view', 'customRules' => []],
                ['permission' => 'job.create', 'customRules' => []],
                ['permission' => 'job.update', 'customRules' => []],
                ['permission' => 'job.delete', 'customRules' => []],
                ['permission' => 'job.statusUpdate', 'customRules' => []],
            ],
        ],
    ];
}
