name: CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test-and-quality:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Install dependencies
        run: composer install --no-progress --prefer-dist

      - name: Setup environment
        run: |
          cp .env.example .env
          php artisan key:generate
      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      # ✅ UNIT TEST
      #- name: Run Unit Tests
      #  run: php artisan test

      # ❌ If test fails → pipeline stops automatically

      # ✅ SONARQUBE SCAN
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v2
        env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: "https://b2f7-2401-4900-8fde-5280-49b6-3600-448c-3d18.ngrok-free.app"

      # ✅ QUALITY GATE CHECK (VERY IMPORTANT)
      - name: Check SonarQube Quality Gate
        run: |
          sleep 10
          STATUS=$(curl -s -u ${{ secrets.SONAR_TOKEN }}: \
          "https://b2f7-2401-4900-8fde-5280-49b6-3600-448c-3d18.ngrok-free.app/api/qualitygates/project_status?projectKey=spontaine-demo" \
          | jq -r '.projectStatus.status')

          echo "Quality Gate Status: $STATUS"

          if [ "$STATUS" != "OK" ]; then
            echo "❌ Quality Gate Failed"
            exit 1
          fi
